### ISSUE TITLE
Finish recording frontend

### ISSUE THREAD

**Issue by pbtan999** [ksulaoja/zoom-analyzer#22]
- change home page (add recording) save button from green to #0039ad
- add recording length limit 90minutes (a slider maybe?), minimum 5 min

- add recording post request returns token. Use that token to redirect user to the detail view. All GET requests made to the backend have to include request parameter "token" with the correct value.
- read token from url when user clicks the link in their email. E.g. user gets an email with this link: http://localhost:3000/recordings/recording/1?token=fkmakfmak
Read the token and use it to request data about that recording.

- remove token from detail view table
- Add ZOOMALYZER title to the page
- remove "recordings" button from navbar
- add text to add recording page. "A link containing the status and the recording will be sent to your email. You will be notified via email if the recording fails."

**Comment by ksulaoja** [comment]
// Time spent 7h. Fronti täiendused

**Comment by ksulaoja** [comment]
// Time spent 1h. Meeting with Paul

**Comment by ksulaoja** [comment]
// Time spent 1h. Disable download button if status not FAILED/ENDED
